// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFlHz5BjjR0EU8O29ohcfp87WoagCCnyM',
    appId: '1:599146157643:web:c753a0acaa6fa2d104dfce',
    messagingSenderId: '599146157643',
    projectId: 'bookswap-35ac9',
    authDomain: 'bookswap-35ac9.firebaseapp.com',
    storageBucket: 'bookswap-35ac9.firebasestorage.app',
    measurementId: 'G-09PX9YDCE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFlHz5BjjR0EU8O29ohcfp87WoagCCnyM',
    appId: '1:599146157643:android:c753a0acaa6fa2d104dfce',
    messagingSenderId: '599146157643',
    projectId: 'bookswap-35ac9',
    storageBucket: 'bookswap-35ac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFlHz5BjjR0EU8O29ohcfp87WoagCCnyM',
    appId: '1:599146157643:ios:c753a0acaa6fa2d104dfce',
    messagingSenderId: '599146157643',
    projectId: 'bookswap-35ac9',
    storageBucket: 'bookswap-35ac9.firebasestorage.app',
    iosClientId: '599146157643-hbrc7l4v0v2e3arqm3agjjt8ot53pehc.apps.googleusercontent.com',
    iosBundleId: 'com.example.book_swap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFlHz5BjjR0EU8O29ohcfp87WoagCCnyM',
    appId: '1:599146157643:ios:c753a0acaa6fa2d104dfce',
    messagingSenderId: '599146157643',
    projectId: 'bookswap-35ac9',
    storageBucket: 'bookswap-35ac9.firebasestorage.app',
    iosClientId: '599146157643-hbrc7l4v0v2e3arqm3agjjt8ot53pehc.apps.googleusercontent.com',
    iosBundleId: 'com.example.book_swap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFlHz5BjjR0EU8O29ohcfp87WoagCCnyM',
    appId: '1:599146157643:web:c753a0acaa6fa2d104dfce',
    messagingSenderId: '599146157643',
    projectId: 'bookswap-35ac9',
    authDomain: 'bookswap-35ac9.firebaseapp.com',
    storageBucket: 'bookswap-35ac9.firebasestorage.app',
    measurementId: 'G-GV4J903Y92',
  );

}